/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 19 14:21:31 GMT 2020
 */

package automated.sg.edu.nus.comp.cs4218.impl.util;


import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

import sg.edu.nus.comp.cs4218.impl.util.StringUtils;

public class StringUtils_ESTest {

  @Test
  public void test0()  throws Throwable  {
      boolean boolean0 = StringUtils.isBlank("\n");
      assertTrue(boolean0);
  }

  @Test
  public void test1()  throws Throwable  {
      boolean boolean0 = StringUtils.isBlank("a?ZA%#0q$80yJ");
      assertFalse(boolean0);
  }

  @Test
  public void test2()  throws Throwable  {
      boolean boolean0 = StringUtils.isBlank((String) null);
      assertTrue(boolean0);
  }

  @Test
  public void test3()  throws Throwable  {
      boolean boolean0 = StringUtils.isBlank("");
      assertTrue(boolean0);
  }

  @Test
  public void test4()  throws Throwable  {
      String[] stringArray0 = StringUtils.tokenize("\n");
      assertEquals(0, stringArray0.length);
  }

  @Test
  public void test5()  throws Throwable  {
      String[] stringArray0 = StringUtils.tokenize("/");
      assertEquals(1, stringArray0.length);
  }

  @Test
  public void test6()  throws Throwable  {
      String string0 = StringUtils.fileSeparator();
      assertEquals("/", string0);
  }
}
