/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 19 16:55:12 GMT 2020
 */

package automated.sg.edu.nus.comp.cs4218.impl.cmd;

import static org.junit.jupiter.api.Assertions.assertNull;

import java.util.List;

import org.junit.jupiter.api.Test;

import sg.edu.nus.comp.cs4218.Command;
import sg.edu.nus.comp.cs4218.impl.cmd.SequenceCommand;

@SuppressWarnings("PMD")
public class SequenceCommand_ESTest {

//  @Test
//  public void test0()  throws Throwable  {
//      SequenceCommand sequenceCommand0 = new SequenceCommand((List<Command>) null);
//      InputStream inputStream0 = mock(InputStream.class, new ViolatedAssumptionAnswer());
//      OutputStream outputStream0 = mock(OutputStream.class, new ViolatedAssumptionAnswer());
//      // Undeclared exception!
//      try {
//        sequenceCommand0.evaluate(inputStream0, outputStream0);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("sg.edu.nus.comp.cs4218.impl.cmd.SequenceCommand", e);
//      }
//  }

  @Test 
  public void test1()  throws Throwable  {
      SequenceCommand sequenceCommand0 = new SequenceCommand((List<Command>) null);
      sequenceCommand0.terminate();
  }

  @Test 
  public void test2()  throws Throwable  {
      SequenceCommand sequenceCommand0 = new SequenceCommand((List<Command>) null);
      List<Command> list0 = sequenceCommand0.getCommands();
      assertNull(list0);
  }
}
