/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 19 14:16:20 GMT 2020
 */

package sg.edu.nus.comp.cs4218.impl.util;


import org.junit.jupiter.api.Test;

public class ErrorConstantsTest {

  @Test
  public void test0()  throws Throwable  {
      ErrorConstants errorConstants0 = new ErrorConstants();
  }
}
